
#!/usr/bin/bash
set -e

for ex in \
	READING_DEV_ID SIMPLE_TX SIMPLE_TX_PDOA SIMPLE_RX RX_SNIFF RX_TRIM RX_DIAG TX_SLEEP \
	TX_SLEEP_IDLE_RC TX_SLEEP_TIMED TX_SLEEP_AUTO TX_WITH_CCA SIMPLE_TX_AES SIMPLE_RX_AES \
	TX_WAIT_RESP TX_WAIT_RESP_INT RX_SEND_RESP SS_TWR_RESPONDER SS_TWR_INITIATOR \
	SS_TWR_INITIATOR_STS SS_TWR_RESPONDER_STS SS_TWR_INITIATOR_STS_NO_DATA SS_TWR_RESPONDER_STS_NO_DATA \
	AES_SS_TWR_INITIATOR AES_SS_TWR_RESPONDER DS_TWR_INITIATOR DS_TWR_RESPONDER \
	DS_TWR_RESPONDER_STS DS_TWR_INITIATOR_STS DS_TWR_STS_SDC_INITIATOR DS_TWR_STS_SDC_RESPONDER \
	CONTINUOUS_WAVE CONTINUOUS_FRAME ACK_DATA_RX ACK_DATA_TX GPIO SIMPLE_TX_STS_SDC SIMPLE_RX_STS_SDC \
	ACK_DATA_RX_DBL_BUFF SPI_CRC SIMPLE_RX_PDOA OTP_WRITE LE_PEND_TX LE_PEND_RX:
do
	rm -r build
	cmake -B build -DBOARD_ROOT=. -DBOARD=minew_ms151f7 -DEXAMPLE=$ex  .
	make -C build
done
